// Assembly PaintDotNet, Version 3.511.4977.23448

[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Reflection.AssemblyTitle("Paint.NET")]
[assembly: System.Reflection.AssemblyDescription("Image and photo editing software.")]
[assembly: System.Runtime.CompilerServices.Dependency("WindowsBase", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Runtime.CompilerServices.Extension]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 2013 dotPDN LLC, Rick Brewster, and past contributors. All Rights Reserved.")]
[assembly: System.Runtime.CompilerServices.Dependency("System.Windows.Forms", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Reflection.AssemblyCompany("dotPDN LLC")]
[assembly: System.Reflection.AssemblyProduct("Paint.NET")]
[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyTrademark("Paint.NET is a registered trademark of dotPDN LLC")]
[assembly: System.Reflection.AssemblyDelaySign(false)]
[assembly: System.Runtime.CompilerServices.StringFreezing]
[assembly: System.Runtime.CompilerServices.Dependency("System.Core", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Runtime.CompilerServices.Dependency("System.Drawing", System.Runtime.CompilerServices.LoadHint.Always)]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, SkipVerification=true)]

